# Default classification configuration

name: template_classifier  # Classifier implementation to use
                       # Options: template_classifier, cnn_classifier, hybrid_classifier

# Template classifier settings
template:
  template_dir: "${base_dir}/models/templates"  # Directory for storing templates
  template_size: [64, 64]           # Size for template images
  method: "cv2.TM_SQDIFF_NORMED"    # Template matching method (changed from TM_CCORR_NORMED)
  threshold: 0.15                   # 降低匹配阈值，提高系统对弱匹配的接受程度

# CNN classifier settings
cnn:
  model_path: "${base_dir}/models/cnn/best_model.h5"  # Path for saving/loading CNN model
  input_shape: [64, 64, 3]           # Input image shape
  num_classes: 14                    # Number of metro line classes
  architecture: "mobilenet"          # Model architecture
  dropout_rate: 0.5                  # Dropout rate
  use_augmentation: true             # Whether to use data augmentation
  weights: null                      # Pre-trained weights path (null for none)
  
# Hybrid classifier settings
hybrid:
  primary: "cnn"                     # Primary classifier (cnn or template)
  fallback_threshold: 0.6            # Threshold to trigger fallback classifier
  
# Common settings
threshold: 0.5                       # Classification confidence threshold
preprocess_input: true               # Whether to preprocess images before classification 

# 线路特定设置
line_specific:
  # 对常被漏检的线路使用较低的阈值
  "11": 
    threshold: 0.12
    weight_multiplier: 1.2  # 增加该线路的权重
  "7": 
    threshold: 0.15
    weight_multiplier: 1.1
  # 针对容易误识别为背景的线路
  "1": 
    edge_ratio_min: 0.008  # 降低边缘比率检查门槛
  "14": 
    edge_ratio_min: 0.008 