# ROI Dataset Configuration for Classification

# ROI extraction and dataset generation
name: roi_dataset
roi_dataset:
  roi_dataset_dir: ${base_dir}/data
  add_background_samples: true
  background_class_id: -1
  num_bg_samples_per_image: 2
  random_seed: ${seed}  # Use seed from main config

  # Dataset structure
  train_dir: ${base_dir}/data/train
  val_dir: ${base_dir}/data/val
  test_dir: ${base_dir}/data/test

  # Auto-generation settings
  auto_generate: true
  use_preprocessed_rois: true 