# CNN Preprocessing Configuration

# Image preprocessing settings
name: cnn_preprocessing
cnn_preprocessing:
  target_size: [64, 64]  # Size for resizing images (width, height)
  normalize: true        # Normalize pixel values to [0,1]
  channel_order: rgb     # Color channel order ('rgb' or 'bgr')

  # Data augmentation settings (for training)
  use_augmentation: true   # Whether to use data augmentation
  rotation_range: 10       # Rotation range in degrees
  width_shift_range: 0.1   # Width shift range as fraction of width
  height_shift_range: 0.1  # Height shift range as fraction of height
  horizontal_flip: false   # Whether to randomly flip images horizontally
  zoom_range: 0.1          # Range for random zoom
  brightness_range: [0.9, 1.1]  # Range for random brightness adjustment 